import { Dimensions, StyleSheet } from "react-native";
import Colors from "../../assets/Colors";

const AuthStyleSheet = StyleSheet.create({
    mainView:{
        height:Dimensions.get('screen').height,
        justifyContent:'space-between',
        alignItems:'center',
        paddingBottom:40,
        width:'100%',
    },
    downView:{
        gap:20,
        width:'100%',
        btns:{
            flexDirection:'row',
            gap:20
        },
        justifyContent:'center',
        alignItems:'center',
        text:{
            textAlign:'center',
            color:Colors.bgCol,
            fontFamily:'Regular',
            fontSize:12,
        },
    },
    
    boxView:{
        backgroundColor:Colors.bgCol,
        btn:{
            marginTop:20,
            flexDirection:'row',
            width:'100%',
            justifyContent:'space-between',
            alignItems:'center',
            borderRadius:50,
            backgroundColor:Colors.mainCol,
            overflow:'hidden',
            text:{
                fontFamily:'Regular',
                fontSize:15,
                textTransform:'capitalize',
                textAlign:'right',
                textAlignVertical:'center',
                color:Colors.bgCol,
                width:'60%'
            }
        },
        width:'80%',
        padding:20,
        borderRadius:20,
        marginBottom:30,
        justifyContent:'center',
        alignItems:'center',
        title:{
            fontFamily:'Bold',
            fontSize:20,
            textAlign:'center',
            width:'100%',
            textAlignVertical:'center',
            marginBottom:10
        },
        textInput:{
            fontFamily:'Regular',
            fontSize:12,
            textAlign:'left',
            width:'100%',
            borderColor:Colors.secCol,
            borderBottomWidth:.5,
            padding:2.5,
            marginBottom:10
        },
        text:{
            marginTop:10,
            textAlign:'right',
            color:Colors.mainCol,
            fontFamily:'Regular',
            fontSize:12,
        },
        zIndex:0
    },
    sideDummyView:{
        backgroundColor:'rgba(255,255,255,.2)',
        height:200,
        width:'100%',
        position:'absolute',
        top:'-5%',
        borderRadius:10,
        zIndex:-1
    },
    checkboxView:{
        width:'100%',
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
        gap:10,
        text:{
            fontSize:12,
            fontFamily:'Regular',
        },
        marginTop:10,
        marginBottom:10
    },
    titleText:{
        fontFamily:'Regular',
        fontSize:12,
        textTransform:'capitalize',
        color:Colors.navCol
    },
    inputView:{
        width:'100%',
        flexDirection:'row',
        gap:10,
        justifyContent:'center',
        alignItems:'center',
        textInput:{
            borderBottomWidth:1,
            borderColor:Colors.mainCol,
            padding:10,
            fontFamily:'Regular',
            fontSize:12,
            textAlign:'center',
            textAlignVertical:'center'
        },
        marginBottom:10
    }
});

export default AuthStyleSheet;